#!/bin/sh

# scans a DIN A4 document with 300 dpi and directly prints it
# scanimage options are tuned for Canon LiDE 210

TMPFILE="/tmp/scan.tiff"
LOCKFILE="/tmp/insaned-scan.lock"
INSANED_LOGFILE="/tmp/insaned.log"

# shamelessly stolen from scanbuttond and modified for Canon LiDE 210 and Canon Pixma IP4000
# respectively
#
# This example turns your scanner+printer into a photocopier.
# Fine-tuned for the Epson Perfection 2400, the HP LaserJet 1200 and
# ISO A4 paper size so that the scanned document matches the printer
# output as closely as possible.

if [ -f "$LOCKFILE" ]; then
    echo "Error: Another scanning operation is currently in progress" >> "$INSANED_LOGFILE"
    exit 0
fi
# cleanup on exit
finish() {
    rm -f "$LOCKFILE" >/dev/null 2>&1
}
trap finish EXIT
touch "$LOCKFILE"


rm -f "$TMPFILE" >/dev/null 2>&1

# for Canon LiDE 210
scanimage --device-name "$1" --format tiff --mode Gray \
    -l 2 -t 0 -x 206 -y 293 --resolution 300 --contrast 18 --brightness 4 --swdespeck=yes --despeck 3 > "$TMPFILE"

tiff2ps -c -w 8.11 -h 11.54 "$TMPFILE" | lpr >> "$INSANED_LOGFILE" 2>&1 &

